sudo: required
services:
- docker
language: shell
dist: bionic
os: linux
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - DOCKER_PLATFORMS='linux/arm64 linux/arm/v7'
  - TAGS='latest'
  - secure: horFz//3hwjFHX9wKIjubgYgcKppwyn7EpnZoH6ZtAibwXai/N1Zy9Mk9j65+nsOdlzxTL14TDNE+kN5/K5ZN/fcp+VDZOor+4LF3hmJXjpYbpPVN3GM8DgkUvMbHUNfKDCiBWlavOMaU8oYqFFzAlUvLMGui1i3Kdhoii2OnLtbA5MaLqBHl+Ed7iOBLD7fgljL0xJT7rvNW28TKcAxLWbtmFyRCEa3AFq7oLHlUSZCrB5Vs4CuTUCVs2QNC61PoXR7z31M5r6FIg2bxuA6Jy3AU8AzFuxZNDH7JpsnPBSIkCCpWGceNmb4A6R0zVAf45/RVSG1F/NAIUlBgVDxkvRVhr5vElmcR0fGEir8HQTnpTCWkAQ0shBbI/+AfgDTULo3p66nWyBJ9TXtSf+CjCKUCb9ExGsfHiXL81hd7MB0PJaYZCRO6dlUD6dja9rAvMneV97k/k+8oulA6gSzzOXLAQ4ADev4Z25qiS4qn/8tq3jLb0jZ8m0YC5toVJuYOhy113uWZBM+pfFtUgX0jJUWM+8/mOMaICUeumNSwnPoJmFFWCRVishY4QzMGjr1AiTTYltjJcNsBh7z+xq/hOmJiEhwihFd66rYO/KTcHj0QuUZDAnWjcqlvwAq08Am83MTjGtXoQyrZk6wfhVi1JGC0oC/n8eR6Kk/inono2g=
  - secure: CVRak7zmwxcrCLvaKgbx0hKmsMrK6ZS2MuhSkHzZsWCVsL1aHjNf+t3G22g+faBEvLumMJbCR/PXx5AzeTpk+bgKrTRFi0wj/n9FHHn2Lq/Rk92NrgaOX70mXeJYhQnfTO1p2ntTfAoUCQ5BHI9hj3TKr68py7WEncNCg3orQDDWURZ/sYw99vVNAO34wjjL1URG+GRNDFBDtN9OOy/Bwh2ECMJdZG6Oitq7NeZmQQPYUC3D1Fu9ceSiFyj61wYANZJBdyjQzjYihCIwnWu6TqE/99PYJAR5zdFZ+j+ikHsMg4h2pGT0auVW/5GPp6rwClKd3y8qZ9o4ZXD1uKlSq02Bn8TrGfPlaTHH3YK1IWdKW4RirH/jPVMjbIpI2l+tXFz7D674WckjObeLS280wS20SeIWyaC+ZT859Sgae72Icv3nMX6bK2rAShM16D0voBgoiPd1FQ7hDyD5NbVTBGmikUERwQr+kZYMcSnHHUIPYvLrvNrNFBkFNNCaXo2bYyeUj2ykbrTaNkXS2Hz8vbjY63QJiSoM4txivvQ2Yk3H7ihkzDtJwgwArvWLu2HD7u9CmY5okNv4+YEXzijqcgBPqZnjpXa+c+rYzQx/pXPbElO5p59OhmDhQQ2o5uI0JTQpsIUmGFtJbRqUwkGYA9XdziygOyd+cywVp0HDrm0=
  - secure: e7VSWC16eS/h1r+51WZDn9DJJTO6BOVL8HTaU9bTtLzTVNWi+0dkWQfUuh0Uyac+NWMudHChXtmDpLYOjfJ7YASaw4p+kYfdOVxkUW56YVhs0/MIwWr2TiPpMtaZ1oovAeEF6Bbg1qHMCrRBgtTqshNa6IIbjitGse9tBL66lxfesQDzNNVtzWTeYpxhtoiVcWjRa2DN0c3RRi3gPnTiHAAKIYfeB89vX2hT8D/Cy6JCGywWnXCqPf649/rsWA856ABxKiPAFJ3yuIBt90yq2wPLnM0CckmBbvzcB5dSzjDzAjevIaFEWUHt69jaZxvhpaJjdguLC3eg+FAYpgwI1V6+qWQIRzt2YAkaCmA9hObFPlJ+uL8zRjftWsJoCaePtOme9pNHHHMWNUQ7UzNnt1cHjOjZnsvnqcszYDwy8/GDiPvUcIgYE15tBaIGxC+2jDk0ya3rEtuY7hoLdTvm6R6JL7x/hHv3tBkTM0QLG624FyDi2cUvdKakf1039yAU5oS0iYNJgtDtnxAtssCOccmDHep/qjvdgDO/XbsgcqAPNOYMNDviJZXwqshu/vTpeDufvc9JcidvVxlCQ96uRzPuPUYGAEy90iNINjWpTk87GaLk34uQ1PAcV82nylp/IDvUjsM/sHdNlfun8S2R95nn4YqmgGj4iNYwmptbB7w=
jobs:
  fast_finish: true
  include:
  - stage: Deploy docker image
    script:
    - source ./buildx_ci_images.sh
    - set -ex; setup_ci_environment::main; set +x
    - while sleep 300; do echo "still alive"; done &
    - set -ex; build_ci_images::main; set +x

